### ISSUE TITLE
Time Off Power App : approval by direct manager

### ISSUE THREAD

**Issue by ofmano** [aprildunnam/PowerApps#21]
Thank you for your vdo .  please advise me how to set user currently approval by direct manager. Because when I set up everything complete I found that user current show all of manager and anyone can approve. I don't know how to fix it. Thank you in advance

**Comment by aprildunnam** [comment]
I didn't include that in the template because I wanted to leave that open for people to customize since the approver can vary.  To add this in you would add a "Manager" column to the time off requests list. In the app OnStart you can use the Office365Users.GetManager action to put the current logged in users manager in a variable that you can then patch to the list when a record is added.  Then in the Approvals screen you can change the filter and add a for where Manager.Email =yourvariablemanager.email
