### ISSUE TITLE
I followed your instruction but the app has 88 errors

### ISSUE THREAD

**Issue by ahuggard-devere** [aprildunnam/PowerApps#59]
Whist I don't want to waste your valuable time it appears that the instuctions you have posted to create the lists and add the data appears to create 88 error mainly naming issues and I have spent several hours trying to fix I am at a loss, please can you verify that the instructions in perticular the names of the fileds in the list are correct?

Thanks for all your tutorials they are great and i really would appriciate a little assitance in getting this working?

**Comment by TrevorSteel12** [comment]
I've had exactly the same - 88 errors.  It looks like the name given in the ReadMe for the second List is incorrect - it should be "Desk Reservations" rather than "Desk**s** Reservations".  I've renamed the List, then deleted and reinstalled the Powerapp - although I don't know if that last stage was really necessary, it would probably have been enough to just delete and re-linked the data source.  It's still showing 3 warnings - DeskSelect(2) and App(1) - which I'll look in to.

I have also manually created one item directly in each of the Lists, just so that there was some data for the App to work on - again I don't know if that was really necessary.

**Comment by ahuggard-devere** [comment]
Trevor,

Many thanks, I really did not spot that. I will retry and see where I get. Thanks again for the response.

Kind Regards,

Anthony Huggard
Senior Systems Administrator
IT Department

deVere & Partners Holding Limited (C31663)
Tel: +356 21 311 600 | Direct: +356 22 566 171
Email: ***@***.******@***.***>
Address: “Centrepoint”, Dun Karm Street, Birkirkara By-pass, Birkirkara, BKR 9037, Malta

**Comment by aprildunnam** [comment]
Please try the latest version of the app which should resolve most issues: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip

I would also re-check the SP list requirements section to ensure all the field names are correct. That is the cause of most issues.
