### ISSUE TITLE
Time sheet original and V2 no approvals or timesheet view

### ISSUE THREAD

**Issue by nwtravler** [aprildunnam/PowerApps#63]
I can submit a timesheet on both the original and V2 app but nothing shows up in approvals when I test it or I have my direct report test it and nothing shows up in my timesheet history.  The original was a cleaner install than V2, the SharePoint list needs a column named WeekStart instead of Week Start.

**Comment by aprildunnam** [comment]
The filter for the approvals is in the galleries items property:

GroupBy(Filter(
TimeEntries,
Manager.Email = currentUser.Email && Status.Value = "Submitted for Approval"
),"Title","week")

If it isn't showing data then it's most likely because the manager isn't being set correctly. It is filtering to only show items where the current logged in user is listed as the manager in the manager field.

Make sure the "Submit for approval" button has the correct code below to set the manager:

ForAll(
galleryTimeCard.AllItems,
Patch(
TimeEntries,
Defaults(TimeEntries),
{
Title: Text(ddWeeks.Selected.Value,DateTimeFormat.ShortDate) & " - " & Text(ddWeeks.Selected.Value + 6, DateTimeFormat.ShortDate),
'Week Start': ddWeeks.Selected.Value,
Mon: Value(tbMon.Text),
Tues: Value(tbTues.Text),
Weds: Value(tbWed.Text),
Thurs: Value(tbThurs.Text),
Fri: Value(tbFri.Text),
Sat: Value(tbSat.Text),
Sun: Value(tbSun.Text),
Total:Value(tbMon.Text) + Value(tbTues.Text) + Value(tbWed.Text) +
Value(tbThurs.Text) + Value(tbFri.Text) + Value(tbSat.Text) +Value(tbSun.Text),
Comments: tbComments.Text,
Employee: {
'@odata.type': "#Microsoft.Azure.Connectors.SharePoint.SPListExpandedUser",
Claims: "i:0#.f|membership|" & currentUser.Email,
Department: "",
DisplayName: currentUser.FullName,
Email: currentUser.Email,
JobTitle: "",
Picture: ""
},
BillTo: {
'@odata.type': "#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference",
Id: cbBillTo.Selected.ID,
Value: cbBillTo.Selected.Title
},
Manager: {
'@odata.type': "#Microsoft.Azure.Connectors.SharePoint.SPListExpandedUser",
Claims: "i:0#.f|membership|" & Office365Users.ManagerV2(User().Email).mail,
Department: "",
DisplayName: Office365Users.ManagerV2(User().Email).displayName,
Email: Office365Users.ManagerV2(User().Email).mail,
JobTitle: "",
Picture: ""
},
Status: {
ID: 2,
Value: "Submitted for Approval"
}
}
)
);
Set(
successMessage,
"Timesheet Submitted for Approval"
);Refresh(TimeEntries);
Navigate(Success)
