### ISSUE TITLE
Desk Double Booking

### ISSUE THREAD

**Issue by TgrsLdy14** [aprildunnam/PowerApps#76]
Hi!

I followed all the steps and the app works great! Most of the time. There seems to be a problem with times though as it someone has a desk from 7am to 3pm, it allows another user to book that same desk 8am to 5pm. Any ideas why this is??

**Comment by jbeirnemko** [comment]
I have the same issue. Did you find a fix?

**Comment by aprildunnam** [comment]
This could be a date formatting issue.  I will try to find time to look into this. I've been busy with conferences but might have time to look into it next week.

**Comment by 10pizza** [comment]
Thanks April for this template. Big help for our team when opening our new office!

I had the same issue with double booking.  It's due to the filter not filtering out all possible double booking scenario's.

On the desk select screen change the items value of the gallery to:

Filter(Desks;Not(Titel in Filter(
    'Desk Reservations';
    CheckOutFrom >= startTime && CheckOutTo <= endTime || CheckOutFrom <= endTime && CheckOutTo >= endTime  || CheckOutFrom<=startTime && CheckOutTo >= startTime).DeskText))

**Comment by val9ooo** [comment]
Thanks, April for the app. So hopeful!

10pizza thanks for this updated formula, however, I tried it but am still getting the double booking issue.

**Comment by angieJe** [comment]
Hi !
Is there any other solutions to fix this issue?. We are facing double bookings also. I think it's du to the fact some people windows are in french and english and date format is not fix. Could someone please help ?

**Comment by lemming303** [comment]
Hi!
In my case it seems to boil down to this issue:
My SharePoint columns of type DateTime don't store the time correctly. If I pick December 29th 2022, 09:00 to 17:00 it will enter 29.12.2022 00:00 (DD.MM.YYYY hh:mm) in both CheckOutFrom and CheckOutTo, while the "CheckOutFromText" column has the correct value (29.12.2022 09:00 and 29.12.2022 17:00). So any suggested filter based on the CheckOutFrom and CheckOutTo Columns doesn't work for me.

I didn't notice the issue before, because my current version only allows to book a desk for a whole day and my CheckOutFrom/To Columns were set not to show the time, only the date (29.12.2022). I don't have any issues in that version, as long as I don't change the column settings to inlude the time. Once I include the time, I get the double bookings. 

Can anyone confirm the issue?

**Comment by aprildunnam** [comment]
This issue should be resolved in the latest version of the app found here: https://github.com/aprildunnam/PowerApps/blob/master/DeskReservation/solution/DeskBooking2023.zip

**Comment by MikeBetts44** [comment]
> Thanks April for this template. Big help for our team when opening our new office!
> 
> I had the same issue with double booking. It's due to the filter not filtering out all possible double booking scenario's.
> 
> On the desk select screen change the items value of the gallery to:
> 
> Filter(Desks;Not(Titel in Filter( 'Desk Reservations'; CheckOutFrom >= startTime && CheckOutTo <= endTime || CheckOutFrom <= endTime && CheckOutTo >= endTime || CheckOutFrom<=startTime && CheckOutTo >= startTime).DeskText))

Titel? @10pizza
